# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# name: $(majorVersion).$(minorVersion).$(patchVersion)$(channelVersion)$(buildVersion)$(Rev:.r)

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

pool:
  vmImage: "ubuntu-18.04"

variables:
  buildConfiguration: "Release"
  projectName: "Mocoding.AspNetCore.Spa"
  solutionFile: "aspnetcore-spa.sln"  

steps:
  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.0.0'
      useConfigFile: true
      configFilePath: 'GitVersion.yml'
      
  - task: UseDotNet@2
    displayName: 'Install .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.100
      installationPath: $(Agent.ToolsDirectory)/dotnet
      
  - task: DotNetCoreCLI@2
    displayName: "dotnet restore"
    inputs:
      command: restore
      projects: $(solutionFile)

  - task: SonarCloudPrepare@1
    displayName: "Prepare Sonar Cloud"
    inputs:
      SonarCloud: 'sonarcloud'
      organization: 'mocoding'
      scannerMode: 'MSBuild'
      projectKey: 'mocoding-software_aspnetcore-spa'
      extraProperties: 'sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/coverage.opencover.xml'

  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      command: build
      projects: $(solutionFile)

  - task: DotNetCoreCLI@2
    displayName: "dotnet test"
    inputs:
      command: test
      projects: 'test/**/*.Tests.csproj'
      arguments: "--no-build /p:SkipCodeCoverageReport=true /p:Threshold=80 /p:CoverletOutput=$(Agent.TempDirectory)/"

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - task: PublishCodeCoverageResults@1
    displayName: "publish code coverage"
    inputs:
      codeCoverageTool: "Cobertura"
      summaryFileLocation: "$(Agent.TempDirectory)/coverage.cobertura.xml"
    condition: succeededOrFailed()

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack $(projectName)"
    inputs:
      command: pack
      packagesToPack: "src/$(projectName)/$(projectName).csproj"
      configuration: $(buildConfiguration)
      packDirectory: "$(Build.StagingDirectory)/$(projectName)"
      buildProperties: "Version=$(Build.BuildNumber)"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: nupkg"
    inputs:
      PathtoPublish: "$(Build.StagingDirectory)"
      ArtifactName: nupkg
